// Categorised Unicode emoji set for the picker. Not the full Unicode table
// (thousands of entries) but a broad, curated, searchable set. Each entry is
// [emoji, keywords] where keywords are lowercase and space-separated.
export const EMOJI_CATEGORIES = [
  {
    name: 'Smileys & Emotion',
    emojis: [
      ['😀', 'grin happy smile'], ['😃', 'smile happy'], ['😄', 'grin happy laugh'],
      ['😁', 'beam grin happy'], ['😆', 'laugh satisfied'], ['😅', 'sweat smile'],
      ['🤣', 'rofl rolling laugh'], ['😂', 'joy laugh tears'], ['🙂', 'slight smile'],
      ['🙃', 'upside down'], ['😉', 'wink'], ['😊', 'blush smile'],
      ['😇', 'innocent halo angel'], ['🥰', 'love adore'], ['😍', 'heart eyes love'],
      ['🤩', 'star struck'], ['😘', 'kiss love'], ['😗', 'kiss'],
      ['😚', 'kiss blush'], ['😙', 'kiss smile'], ['😋', 'yum tasty'],
      ['😛', 'tongue'], ['😜', 'wink tongue'], ['🤪', 'zany crazy'],
      ['😝', 'tongue squint'], ['🤑', 'money mouth'], ['🤗', 'hug'],
      ['🤭', 'giggle hand mouth'], ['🤫', 'shush quiet'], ['🤔', 'think'],
      ['🤐', 'zipper mouth'], ['🤨', 'raised brow'], ['😐', 'neutral'],
      ['😑', 'expressionless'], ['😶', 'no mouth'], ['😏', 'smirk'],
      ['😒', 'unamused'], ['🙄', 'eye roll'], ['😬', 'grimace'],
      ['🤥', 'lying'], ['😌', 'relieved'], ['😔', 'pensive sad'],
      ['😪', 'sleepy'], ['🤤', 'drool'], ['😴', 'sleep zzz'],
      ['😷', 'mask sick'], ['🤒', 'sick thermometer'], ['🤕', 'hurt bandage'],
      ['🤢', 'nauseated sick'], ['🤮', 'vomit'], ['🥵', 'hot'],
      ['🥶', 'cold freezing'], ['🥴', 'woozy'], ['😵', 'dizzy dead'],
      ['🤯', 'mind blown'], ['🤠', 'cowboy'], ['🥳', 'party celebrate'],
      ['😎', 'cool sunglasses'], ['🤓', 'nerd'], ['🧐', 'monocle'],
      ['😕', 'confused'], ['😟', 'worried'], ['🙁', 'slight frown sad'],
      ['😮', 'open mouth wow'], ['😯', 'hushed'], ['😲', 'astonished'],
      ['😳', 'flushed'], ['🥺', 'pleading'], ['😦', 'frown open'],
      ['😧', 'anguished'], ['😨', 'fearful'], ['😰', 'anxious sweat'],
      ['😥', 'sad relieved'], ['😢', 'cry sad tear'], ['😭', 'sob cry'],
      ['😱', 'scream fear'], ['😖', 'confounded'], ['😣', 'persevere'],
      ['😞', 'disappointed sad'], ['😓', 'sweat downcast'], ['😩', 'weary'],
      ['😫', 'tired'], ['🥱', 'yawn'], ['😤', 'triumph huff'],
      ['😡', 'rage angry'], ['😠', 'angry'], ['🤬', 'cursing swearing'],
      ['😈', 'devil smile'], ['👿', 'devil angry'], ['💀', 'skull dead'],
      ['💩', 'poop'], ['🤡', 'clown'], ['👻', 'ghost'],
      ['👽', 'alien'], ['🤖', 'robot'], ['😺', 'cat smile'],
      ['😹', 'cat joy'], ['😻', 'cat heart eyes'], ['🙀', 'cat scream'],
      ['❤️', 'heart love red'], ['🧡', 'orange heart'], ['💛', 'yellow heart'],
      ['💚', 'green heart'], ['💙', 'blue heart'], ['💜', 'purple heart'],
      ['🖤', 'black heart'], ['🤍', 'white heart'], ['💔', 'broken heart'],
      ['❣️', 'heart exclamation'], ['💕', 'two hearts'], ['💞', 'revolving hearts'],
      ['💓', 'beating heart'], ['💗', 'growing heart'], ['💖', 'sparkling heart'],
      ['💘', 'heart arrow'], ['💝', 'heart gift'], ['💯', 'hundred 100'],
      ['💢', 'anger symbol'], ['💥', 'boom collision'], ['💫', 'dizzy star'],
      ['💦', 'sweat drops'], ['💨', 'dash wind'], ['🕳️', 'hole'],
      ['💬', 'speech bubble'], ['💭', 'thought bubble'], ['💤', 'zzz sleep'],
    ],
  },
  {
    name: 'People & Body',
    emojis: [
      ['👋', 'wave hello bye'], ['🤚', 'raised back hand'], ['🖐️', 'hand fingers'],
      ['✋', 'raised hand stop'], ['🖖', 'vulcan spock'], ['👌', 'ok hand'],
      ['🤌', 'pinched fingers'], ['🤏', 'pinch small'], ['✌️', 'peace victory'],
      ['🤞', 'crossed fingers luck'], ['🤟', 'love you gesture'], ['🤘', 'rock sign'],
      ['🤙', 'call me'], ['👈', 'point left'], ['👉', 'point right'],
      ['👆', 'point up'], ['👇', 'point down'], ['☝️', 'index up'],
      ['👍', 'thumbsup like yes'], ['👎', 'thumbsdown dislike no'], ['✊', 'fist raised'],
      ['👊', 'fist bump'], ['🤛', 'fist left'], ['🤜', 'fist right'],
      ['👏', 'clap applause'], ['🙌', 'raise hands hooray'], ['👐', 'open hands'],
      ['🤲', 'palms up'], ['🤝', 'handshake deal'], ['🙏', 'pray please thanks'],
      ['✍️', 'writing hand'], ['💅', 'nail polish'], ['🤳', 'selfie'],
      ['💪', 'muscle strong'], ['🦵', 'leg'], ['🦶', 'foot'],
      ['👂', 'ear'], ['👃', 'nose'], ['🧠', 'brain'],
      ['👀', 'eyes look'], ['👁️', 'eye'], ['👅', 'tongue'],
      ['👄', 'mouth lips'], ['👶', 'baby'], ['🧒', 'child'],
      ['👦', 'boy'], ['👧', 'girl'], ['🧑', 'person'],
      ['👨', 'man'], ['👩', 'woman'], ['🧓', 'older person'],
      ['👴', 'old man'], ['👵', 'old woman'], ['🙍', 'frown person'],
      ['🙎', 'pouting person'], ['🙅', 'no gesture'], ['🙆', 'ok gesture'],
      ['💁', 'info desk'], ['🙋', 'raising hand'], ['🧏', 'deaf person'],
      ['🙇', 'bow'], ['🤦', 'facepalm'], ['🤷', 'shrug'],
      ['👮', 'police officer'], ['🕵️', 'detective'], ['💂', 'guard'],
      ['👷', 'construction worker'], ['🤴', 'prince'], ['👸', 'princess'],
      ['👳', 'turban person'], ['👰', 'bride'], ['🤵', 'tuxedo'],
      ['🦸', 'superhero'], ['🦹', 'supervillain'], ['🧙', 'mage wizard'],
      ['🧚', 'fairy'], ['🧛', 'vampire'], ['🧜', 'mermaid'],
      ['🧝', 'elf'], ['🧞', 'genie'], ['💃', 'dancer woman'],
      ['🕺', 'dancer man'], ['👯', 'people dancing'], ['🧖', 'sauna'],
      ['🚶', 'walking'], ['🏃', 'running'], ['💇', 'haircut'],
      ['💆', 'massage'], ['🛀', 'bath'], ['🛌', 'sleeping bed'],
    ],
  },
  {
    name: 'Animals & Nature',
    emojis: [
      ['🐶', 'dog puppy'], ['🐱', 'cat kitten'], ['🐭', 'mouse'],
      ['🐹', 'hamster'], ['🐰', 'rabbit bunny'], ['🦊', 'fox'],
      ['🐻', 'bear'], ['🐼', 'panda'], ['🐨', 'koala'],
      ['🐯', 'tiger'], ['🦁', 'lion'], ['🐮', 'cow'],
      ['🐷', 'pig'], ['🐸', 'frog'], ['🐵', 'monkey'],
      ['🙈', 'monkey see no evil'], ['🙉', 'monkey hear no evil'], ['🙊', 'monkey speak no evil'],
      ['🐔', 'chicken'], ['🐧', 'penguin'], ['🐦', 'bird'],
      ['🐤', 'chick'], ['🦆', 'duck'], ['🦅', 'eagle'],
      ['🦉', 'owl'], ['🦇', 'bat'], ['🐺', 'wolf'],
      ['🐗', 'boar'], ['🐴', 'horse'], ['🦄', 'unicorn'],
      ['🐝', 'bee'], ['🐛', 'bug'], ['🦋', 'butterfly'],
      ['🐌', 'snail'], ['🐞', 'ladybug'], ['🐜', 'ant'],
      ['🕷️', 'spider'], ['🦂', 'scorpion'], ['🐢', 'turtle'],
      ['🐍', 'snake'], ['🦎', 'lizard'], ['🐙', 'octopus'],
      ['🦑', 'squid'], ['🦐', 'shrimp'], ['🦀', 'crab'],
      ['🐡', 'blowfish'], ['🐠', 'tropical fish'], ['🐟', 'fish'],
      ['🐬', 'dolphin'], ['🐳', 'whale'], ['🦈', 'shark'],
      ['🐊', 'crocodile'], ['🐅', 'tiger2'], ['🐆', 'leopard'],
      ['🦓', 'zebra'], ['🦍', 'gorilla'], ['🐘', 'elephant'],
      ['🦏', 'rhino'], ['🐪', 'camel'], ['🦒', 'giraffe'],
      ['🐃', 'water buffalo'], ['🐎', 'racehorse'], ['🐖', 'pig2'],
      ['🐏', 'ram'], ['🐑', 'sheep'], ['🦙', 'llama'],
      ['🐐', 'goat'], ['🦌', 'deer'], ['🐕', 'dog2'],
      ['🐩', 'poodle'], ['🐈', 'cat2'], ['🐓', 'rooster'],
      ['🦃', 'turkey'], ['🦚', 'peacock'], ['🦜', 'parrot'],
      ['🦢', 'swan'], ['🕊️', 'dove peace'], ['🐇', 'rabbit2'],
      ['🦝', 'raccoon'], ['🦥', 'sloth'], ['🦦', 'otter'],
      ['🦔', 'hedgehog'], ['🐾', 'paw prints'], ['🌵', 'cactus'],
      ['🎄', 'christmas tree'], ['🌲', 'evergreen tree'], ['🌳', 'tree'],
      ['🌴', 'palm tree'], ['🌱', 'seedling'], ['🌿', 'herb'],
      ['☘️', 'shamrock'], ['🍀', 'four leaf clover'], ['🎍', 'bamboo'],
      ['🌾', 'rice'], ['🌺', 'hibiscus'], ['🌻', 'sunflower'],
      ['🌹', 'rose'], ['🥀', 'wilted flower'], ['🌷', 'tulip'],
      ['🌸', 'cherry blossom'], ['💐', 'bouquet'], ['🌼', 'blossom'],
      ['🌞', 'sun face'], ['🌝', 'full moon face'], ['🌚', 'new moon face'],
      ['🌙', 'moon crescent'], ['⭐', 'star'], ['🌟', 'glowing star'],
      ['✨', 'sparkles'], ['⚡', 'lightning bolt'], ['☀️', 'sun'],
      ['⛅', 'partly cloudy'], ['☁️', 'cloud'], ['🌧️', 'rain'],
      ['⛈️', 'thunder rain'], ['❄️', 'snowflake'], ['☃️', 'snowman'],
      ['🌈', 'rainbow'], ['💧', 'droplet'], ['🌊', 'wave water'],
      ['🔥', 'fire flame'], ['💥', 'boom'],
    ],
  },
  {
    name: 'Food & Drink',
    emojis: [
      ['🍏', 'green apple'], ['🍎', 'apple'], ['🍐', 'pear'],
      ['🍊', 'orange tangerine'], ['🍋', 'lemon'], ['🍌', 'banana'],
      ['🍉', 'watermelon'], ['🍇', 'grapes'], ['🍓', 'strawberry'],
      ['🫐', 'blueberries'], ['🍈', 'melon'], ['🍒', 'cherries'],
      ['🍑', 'peach'], ['🥭', 'mango'], ['🍍', 'pineapple'],
      ['🥥', 'coconut'], ['🥝', 'kiwi'], ['🍅', 'tomato'],
      ['🍆', 'eggplant'], ['🥑', 'avocado'], ['🥦', 'broccoli'],
      ['🥬', 'leafy green'], ['🥒', 'cucumber'], ['🌶️', 'hot pepper'],
      ['🌽', 'corn'], ['🥕', 'carrot'], ['🧄', 'garlic'],
      ['🧅', 'onion'], ['🥔', 'potato'], ['🍠', 'sweet potato'],
      ['🥐', 'croissant'], ['🥯', 'bagel'], ['🍞', 'bread'],
      ['🥖', 'baguette'], ['🧀', 'cheese'], ['🥚', 'egg'],
      ['🍳', 'cooking egg'], ['🥞', 'pancakes'], ['🧇', 'waffle'],
      ['🥓', 'bacon'], ['🍔', 'burger'], ['🍟', 'fries'],
      ['🍕', 'pizza'], ['🌭', 'hotdog'], ['🥪', 'sandwich'],
      ['🌮', 'taco'], ['🌯', 'burrito'], ['🥙', 'pita'],
      ['🧆', 'falafel'], ['🥘', 'pan food'], ['🍝', 'pasta'],
      ['🍜', 'ramen noodles'], ['🍲', 'stew'], ['🍛', 'curry rice'],
      ['🍣', 'sushi'], ['🍱', 'bento'], ['🥟', 'dumpling'],
      ['🍤', 'fried shrimp'], ['🍙', 'rice ball'], ['🍚', 'rice'],
      ['🍘', 'rice cracker'], ['🍥', 'fish cake'], ['🥠', 'fortune cookie'],
      ['🍢', 'oden'], ['🍡', 'dango'], ['🍧', 'shaved ice'],
      ['🍨', 'ice cream'], ['🍦', 'soft ice cream'], ['🥧', 'pie'],
      ['🧁', 'cupcake'], ['🍰', 'cake'], ['🎂', 'birthday cake'],
      ['🍮', 'custard'], ['🍭', 'lollipop'], ['🍬', 'candy'],
      ['🍫', 'chocolate'], ['🍿', 'popcorn'], ['🍩', 'donut'],
      ['🍪', 'cookie'], ['🌰', 'chestnut'], ['🥜', 'peanuts'],
      ['🍯', 'honey'], ['🥛', 'milk'], ['🍼', 'baby bottle'],
      ['☕', 'coffee tea'], ['🍵', 'tea'], ['🧋', 'bubble tea'],
      ['🥤', 'cup straw'], ['🍶', 'sake'], ['🍺', 'beer'],
      ['🍻', 'beers cheers'], ['🥂', 'clink glasses'], ['🍷', 'wine'],
      ['🥃', 'whiskey'], ['🍸', 'cocktail'], ['🍹', 'tropical drink'],
      ['🧉', 'mate'], ['🍾', 'champagne'],
    ],
  },
  {
    name: 'Activities',
    emojis: [
      ['⚽', 'soccer football'], ['🏀', 'basketball'], ['🏈', 'american football'],
      ['⚾', 'baseball'], ['🥎', 'softball'], ['🎾', 'tennis'],
      ['🏐', 'volleyball'], ['🏉', 'rugby'], ['🥏', 'frisbee'],
      ['🎱', 'pool 8ball'], ['🪀', 'yo yo'], ['🏓', 'ping pong'],
      ['🏸', 'badminton'], ['🏒', 'hockey'], ['🏑', 'field hockey'],
      ['🥍', 'lacrosse'], ['🏏', 'cricket'], ['🥅', 'goal net'],
      ['⛳', 'golf'], ['🪁', 'kite'], ['🏹', 'bow arrow'],
      ['🎣', 'fishing'], ['🤿', 'diving mask'], ['🥊', 'boxing glove'],
      ['🥋', 'martial arts'], ['🎽', 'running shirt'], ['🛹', 'skateboard'],
      ['🛼', 'roller skate'], ['🛷', 'sled'], ['⛸️', 'ice skate'],
      ['🥌', 'curling'], ['🎿', 'ski'], ['⛷️', 'skier'],
      ['🏂', 'snowboard'], ['🪂', 'parachute'], ['🏋️', 'weight lift'],
      ['🤼', 'wrestling'], ['🤸', 'cartwheel'], ['⛹️', 'basketball player'],
      ['🤺', 'fencing'], ['🤾', 'handball'], ['🏌️', 'golfing'],
      ['🏇', 'horse racing'], ['🧘', 'yoga meditate'], ['🏄', 'surfing'],
      ['🏊', 'swimming'], ['🤽', 'water polo'], ['🚣', 'rowing'],
      ['🧗', 'climbing'], ['🚵', 'mountain biking'], ['🚴', 'cycling'],
      ['🏆', 'trophy win'], ['🥇', 'gold medal first'], ['🥈', 'silver medal'],
      ['🥉', 'bronze medal'], ['🏅', 'sports medal'], ['🎖️', 'military medal'],
      ['🎗️', 'reminder ribbon'], ['🎫', 'ticket'], ['🎟️', 'admission ticket'],
      ['🎪', 'circus tent'], ['🤹', 'juggling'], ['🎭', 'performing arts theatre'],
      ['🩰', 'ballet'], ['🎨', 'art palette'], ['🎬', 'clapper movie'],
      ['🎤', 'microphone'], ['🎧', 'headphones'], ['🎼', 'musical score'],
      ['🎹', 'piano'], ['🥁', 'drum'], ['🎷', 'saxophone'],
      ['🎺', 'trumpet'], ['🎸', 'guitar'], ['🪕', 'banjo'],
      ['🎻', 'violin'], ['🎲', 'dice'], ['♟️', 'chess pawn'],
      ['🎯', 'dart target'], ['🎳', 'bowling'], ['🎮', 'video game'],
      ['🎰', 'slot machine'], ['🧩', 'puzzle'],
    ],
  },
  {
    name: 'Travel & Places',
    emojis: [
      ['🚗', 'car'], ['🚕', 'taxi'], ['🚙', 'suv'],
      ['🚌', 'bus'], ['🚎', 'trolleybus'], ['🏎️', 'race car'],
      ['🚓', 'police car'], ['🚑', 'ambulance'], ['🚒', 'fire engine'],
      ['🚐', 'minibus'], ['🚚', 'truck'], ['🚛', 'lorry'],
      ['🚜', 'tractor'], ['🏍️', 'motorcycle'], ['🛵', 'scooter'],
      ['🚲', 'bicycle'], ['🛴', 'kick scooter'], ['🚨', 'police light'],
      ['🚔', 'oncoming police'], ['🚍', 'oncoming bus'], ['🚘', 'oncoming car'],
      ['🚖', 'oncoming taxi'], ['🚡', 'cable car'], ['🚠', 'mountain cable car'],
      ['🚟', 'suspension railway'], ['🚃', 'railway car'], ['🚋', 'tram'],
      ['🚞', 'mountain railway'], ['🚝', 'monorail'], ['🚄', 'high speed train'],
      ['🚅', 'bullet train'], ['🚈', 'light rail'], ['🚂', 'steam train'],
      ['🚆', 'train'], ['🚇', 'metro'], ['🚊', 'tram2'],
      ['🚉', 'station'], ['✈️', 'airplane flight'], ['🛫', 'takeoff'],
      ['🛬', 'landing'], ['🛩️', 'small plane'], ['💺', 'seat'],
      ['🛰️', 'satellite'], ['🚀', 'rocket launch'], ['🛸', 'ufo'],
      ['🚁', 'helicopter'], ['🛶', 'canoe'], ['⛵', 'sailboat'],
      ['🚤', 'speedboat'], ['🛥️', 'motor boat'], ['🛳️', 'passenger ship'],
      ['⛴️', 'ferry'], ['🚢', 'ship'], ['⚓', 'anchor'],
      ['⛽', 'fuel pump'], ['🚧', 'construction barrier'], ['🚦', 'traffic light'],
      ['🚥', 'horizontal traffic light'], ['🗺️', 'map'], ['🗿', 'moai statue'],
      ['🗽', 'statue of liberty'], ['🗼', 'tokyo tower'], ['🏰', 'castle'],
      ['🏯', 'japanese castle'], ['🏟️', 'stadium'], ['🎡', 'ferris wheel'],
      ['🎢', 'roller coaster'], ['🎠', 'carousel'], ['⛲', 'fountain'],
      ['⛱️', 'beach umbrella'], ['🏖️', 'beach'], ['🏝️', 'desert island'],
      ['🏜️', 'desert'], ['🌋', 'volcano'], ['⛰️', 'mountain'],
      ['🏔️', 'snow mountain'], ['🗻', 'mount fuji'], ['🏕️', 'camping'],
      ['⛺', 'tent'], ['🏠', 'house home'], ['🏡', 'house garden'],
      ['🏘️', 'houses'], ['🏚️', 'derelict house'], ['🏗️', 'construction'],
      ['🏭', 'factory'], ['🏢', 'office building'], ['🏬', 'department store'],
      ['🏣', 'post office'], ['🏤', 'european post office'], ['🏥', 'hospital'],
      ['🏦', 'bank'], ['🏨', 'hotel'], ['🏪', 'convenience store'],
      ['🏫', 'school'], ['🏩', 'love hotel'], ['💒', 'wedding chapel'],
      ['🏛️', 'classical building'], ['⛪', 'church'], ['🕌', 'mosque'],
      ['🛕', 'hindu temple'], ['🕍', 'synagogue'], ['🕋', 'kaaba'],
    ],
  },
  {
    name: 'Objects',
    emojis: [
      ['⌚', 'watch'], ['📱', 'phone mobile'], ['📲', 'phone arrow'],
      ['💻', 'laptop computer'], ['⌨️', 'keyboard'], ['🖥️', 'desktop computer'],
      ['🖨️', 'printer'], ['🖱️', 'mouse computer'], ['🖲️', 'trackball'],
      ['💽', 'minidisc'], ['💾', 'floppy disk save'], ['💿', 'cd'],
      ['📀', 'dvd'], ['📼', 'vhs tape'], ['📷', 'camera'],
      ['📸', 'camera flash'], ['📹', 'video camera'], ['🎥', 'movie camera'],
      ['📽️', 'film projector'], ['🎞️', 'film frames'], ['📞', 'telephone'],
      ['☎️', 'phone'], ['📟', 'pager'], ['📠', 'fax'],
      ['📺', 'tv television'], ['📻', 'radio'], ['🎙️', 'studio microphone'],
      ['🎚️', 'level slider'], ['🎛️', 'control knobs'], ['🧭', 'compass'],
      ['⏱️', 'stopwatch'], ['⏲️', 'timer clock'], ['⏰', 'alarm clock'],
      ['🕰️', 'mantelpiece clock'], ['⌛', 'hourglass done'], ['⏳', 'hourglass'],
      ['📡', 'satellite antenna'], ['🔋', 'battery'], ['🔌', 'plug'],
      ['💡', 'light bulb idea'], ['🔦', 'flashlight'], ['🕯️', 'candle'],
      ['🪔', 'diya lamp'], ['🧯', 'fire extinguisher'], ['🛢️', 'oil drum'],
      ['💸', 'money with wings'], ['💵', 'dollar banknote'], ['💴', 'yen banknote'],
      ['💶', 'euro banknote'], ['💷', 'pound banknote'], ['💰', 'money bag'],
      ['💳', 'credit card'], ['💎', 'gem diamond'], ['⚖️', 'scales balance'],
      ['🧰', 'toolbox'], ['🔧', 'wrench'], ['🔨', 'hammer'],
      ['⚒️', 'hammer pick'], ['🛠️', 'hammer wrench'], ['⛏️', 'pick'],
      ['🔩', 'nut bolt'], ['⚙️', 'gear settings'], ['🧱', 'brick'],
      ['⛓️', 'chains'], ['🧲', 'magnet'], ['🔫', 'water pistol'],
      ['💣', 'bomb'], ['🧨', 'firecracker'], ['🪓', 'axe'],
      ['🔪', 'knife'], ['🗡️', 'dagger'], ['⚔️', 'crossed swords'],
      ['🛡️', 'shield'], ['🚬', 'cigarette'], ['⚰️', 'coffin'],
      ['🪦', 'headstone'], ['⚱️', 'funeral urn'], ['🏺', 'amphora'],
      ['🔮', 'crystal ball'], ['📿', 'prayer beads'], ['🧿', 'nazar amulet'],
      ['💈', 'barber pole'], ['⚗️', 'alembic'], ['🔭', 'telescope'],
      ['🔬', 'microscope'], ['🕳️', 'hole'], ['🩹', 'bandage'],
      ['🩺', 'stethoscope'], ['💊', 'pill'], ['💉', 'syringe'],
      ['🩸', 'blood drop'], ['🧬', 'dna'], ['🦠', 'microbe'],
      ['🧫', 'petri dish'], ['🧪', 'test tube'], ['🌡️', 'thermometer'],
      ['🧹', 'broom'], ['🧺', 'basket'], ['🧻', 'toilet paper'],
      ['🚽', 'toilet'], ['🚰', 'potable water'], ['🚿', 'shower'],
      ['🛁', 'bathtub'], ['🛒', 'shopping cart'], ['🚪', 'door'],
      ['🛏️', 'bed'], ['🛋️', 'couch'], ['🪑', 'chair'],
      ['🧸', 'teddy bear'], ['🖼️', 'framed picture'], ['🪞', 'mirror'],
      ['🪟', 'window'], ['🛍️', 'shopping bags'], ['🎁', 'gift present'],
      ['🎈', 'balloon'], ['🎏', 'carp streamer'], ['🎀', 'ribbon'],
      ['🪄', 'magic wand'], ['📦', 'package box'], ['📫', 'mailbox'],
      ['📮', 'postbox'], ['📜', 'scroll'], ['📃', 'page'],
      ['📄', 'page facing up'], ['📑', 'bookmark tabs'], ['🧾', 'receipt'],
      ['📊', 'bar chart'], ['📈', 'chart increasing'], ['📉', 'chart decreasing'],
      ['🗒️', 'spiral notepad'], ['🗓️', 'spiral calendar'], ['📆', 'calendar'],
      ['📅', 'date calendar'], ['📇', 'card index'], ['🗃️', 'card file box'],
      ['🗳️', 'ballot box'], ['🗄️', 'file cabinet'], ['📋', 'clipboard'],
      ['📁', 'folder'], ['📂', 'open folder'], ['🗂️', 'card dividers'],
      ['🗞️', 'rolled newspaper'], ['📰', 'newspaper'], ['📓', 'notebook'],
      ['📔', 'notebook cover'], ['📒', 'ledger'], ['📕', 'closed book'],
      ['📗', 'green book'], ['📘', 'blue book'], ['📙', 'orange book'],
      ['📚', 'books'], ['📖', 'open book'], ['🔖', 'bookmark'],
      ['🔗', 'link'], ['📎', 'paperclip'], ['🖇️', 'linked paperclips'],
      ['📐', 'triangular ruler'], ['📏', 'ruler'], ['🧮', 'abacus'],
      ['📌', 'pushpin'], ['📍', 'round pushpin'], ['✂️', 'scissors'],
      ['🖊️', 'pen'], ['🖋️', 'fountain pen'], ['✒️', 'black nib'],
      ['🖌️', 'paintbrush'], ['🖍️', 'crayon'], ['📝', 'memo write'],
      ['✏️', 'pencil'], ['🔍', 'magnifying glass search'], ['🔎', 'magnifier'],
      ['🔏', 'lock pen'], ['🔐', 'lock key'], ['🔒', 'lock closed'],
      ['🔓', 'lock open'], ['🔑', 'key'], ['🗝️', 'old key'],
    ],
  },
  {
    name: 'Symbols',
    emojis: [
      ['✅', 'check green'], ['☑️', 'checkbox checked'], ['✔️', 'check'],
      ['❌', 'cross x no'], ['❎', 'cross mark'], ['✖️', 'multiply'],
      ['➕', 'plus'], ['➖', 'minus'], ['➗', 'divide'],
      ['♾️', 'infinity'], ['‼️', 'double exclamation'], ['⁉️', 'exclamation question'],
      ['❓', 'question'], ['❔', 'white question'], ['❕', 'white exclamation'],
      ['❗', 'exclamation'], ['〰️', 'wavy dash'], ['💱', 'currency exchange'],
      ['💲', 'dollar sign'], ['⚕️', 'medical symbol'], ['♻️', 'recycle'],
      ['⚜️', 'fleur de lis'], ['🔱', 'trident'], ['📛', 'name badge'],
      ['🔰', 'beginner'], ['⭕', 'hollow red circle'], ['✅', 'check mark button'],
      ['☢️', 'radioactive'], ['☣️', 'biohazard'], ['📴', 'phone off'],
      ['📳', 'vibration'], ['📵', 'no phones'], ['🔞', 'no under 18'],
      ['⚠️', 'warning'], ['🚸', 'children crossing'], ['🔔', 'bell notification'],
      ['🔕', 'bell slash mute'], ['🎵', 'music note'], ['🎶', 'music notes'],
      ['➡️', 'right arrow'], ['⬅️', 'left arrow'], ['⬆️', 'up arrow'],
      ['⬇️', 'down arrow'], ['↗️', 'up right arrow'], ['↘️', 'down right arrow'],
      ['↙️', 'down left arrow'], ['↖️', 'up left arrow'], ['↕️', 'up down arrow'],
      ['↔️', 'left right arrow'], ['↩️', 'right arrow curving left'], ['↪️', 'left arrow curving right'],
      ['⤴️', 'arrow curving up'], ['⤵️', 'arrow curving down'], ['🔃', 'clockwise arrows'],
      ['🔄', 'counterclockwise arrows'], ['🔙', 'back arrow'], ['🔚', 'end arrow'],
      ['🔛', 'on arrow'], ['🔜', 'soon arrow'], ['🔝', 'top arrow'],
      ['🛐', 'place of worship'], ['⚛️', 'atom'], ['🕉️', 'om'],
      ['✡️', 'star of david'], ['☸️', 'dharma wheel'], ['☯️', 'yin yang'],
      ['✝️', 'latin cross'], ['☦️', 'orthodox cross'], ['☪️', 'star crescent'],
      ['☮️', 'peace symbol'], ['🕎', 'menorah'], ['🔯', 'dotted six star'],
      ['♈', 'aries'], ['♉', 'taurus'], ['♊', 'gemini'],
      ['♋', 'cancer'], ['♌', 'leo'], ['♍', 'virgo'],
      ['♎', 'libra'], ['♏', 'scorpio'], ['♐', 'sagittarius'],
      ['♑', 'capricorn'], ['♒', 'aquarius'], ['♓', 'pisces'],
      ['⛎', 'ophiuchus'], ['🔀', 'shuffle'], ['🔁', 'repeat'],
      ['🔂', 'repeat one'], ['▶️', 'play'], ['⏸️', 'pause'],
      ['⏹️', 'stop'], ['⏺️', 'record'], ['⏭️', 'next track'],
      ['⏮️', 'previous track'], ['⏩', 'fast forward'], ['⏪', 'rewind'],
      ['🔼', 'up button'], ['🔽', 'down button'], ['🎦', 'cinema'],
      ['🔅', 'dim brightness'], ['🔆', 'bright brightness'], ['📶', 'signal bars'],
      ['📳', 'vibrate mode'], ['🔇', 'muted speaker'], ['🔈', 'speaker low'],
      ['🔉', 'speaker medium'], ['🔊', 'speaker high'], ['🔔', 'bell'],
      ['#️⃣', 'hash keycap'], ['*️⃣', 'asterisk keycap'], ['0️⃣', 'zero keycap'],
      ['1️⃣', 'one keycap'], ['2️⃣', 'two keycap'], ['3️⃣', 'three keycap'],
      ['4️⃣', 'four keycap'], ['5️⃣', 'five keycap'], ['6️⃣', 'six keycap'],
      ['7️⃣', 'seven keycap'], ['8️⃣', 'eight keycap'], ['9️⃣', 'nine keycap'],
      ['🔟', 'ten'], ['🔠', 'uppercase letters'], ['🔡', 'lowercase letters'],
      ['🔢', 'numbers'], ['🔣', 'symbols input'], ['🔤', 'letters input'],
      ['🅰️', 'a button'], ['🆎', 'ab button'], ['🅱️', 'b button'],
      ['🆑', 'cl button'], ['🆒', 'cool button'], ['🆓', 'free button'],
      ['ℹ️', 'info'], ['🆔', 'id button'], ['Ⓜ️', 'm button'],
      ['🆕', 'new button'], ['🆖', 'ng button'], ['🅾️', 'o button'],
      ['🆗', 'ok button'], ['🅿️', 'p button'], ['🆘', 'sos button'],
      ['🆙', 'up button2'], ['🆚', 'vs button'], ['🈁', 'here button'],
      ['🔚', 'end'], ['🔛', 'on'], ['🔝', 'top'],
    ],
  },
  {
    name: 'Flags',
    emojis: [
      ['🏳️', 'white flag'], ['🏴', 'black flag'], ['🏴‍☠️', 'pirate flag'],
      ['🏁', 'chequered flag finish'], ['🚩', 'triangular flag'], ['🎌', 'crossed flags'],
      ['🏳️‍🌈', 'rainbow flag pride'], ['🏳️‍⚧️', 'transgender flag'],
      ['🇬🇧', 'uk united kingdom britain'], ['🇺🇸', 'usa united states america'],
      ['🇨🇦', 'canada'], ['🇦🇺', 'australia'], ['🇮🇪', 'ireland'],
      ['🇫🇷', 'france'], ['🇩🇪', 'germany'], ['🇪🇸', 'spain'],
      ['🇮🇹', 'italy'], ['🇵🇹', 'portugal'], ['🇳🇱', 'netherlands'],
      ['🇸🇪', 'sweden'], ['🇳🇴', 'norway'], ['🇩🇰', 'denmark'],
      ['🇯🇵', 'japan'], ['🇨🇳', 'china'], ['🇮🇳', 'india'],
      ['🇧🇷', 'brazil'], ['🇲🇽', 'mexico'], ['🇿🇦', 'south africa'],
      ['🇳🇿', 'new zealand'], ['🇰🇷', 'south korea'], ['🇷🇺', 'russia'],
      ['🇺🇦', 'ukraine'], ['🇵🇱', 'poland'], ['🇬🇷', 'greece'],
      ['🇹🇷', 'turkey'], ['🇨🇭', 'switzerland'], ['🇦🇹', 'austria'],
      ['🇧🇪', 'belgium'], ['🇦🇷', 'argentina'], ['🇸🇦', 'saudi arabia'],
      ['🇦🇪', 'uae'], ['🇸🇬', 'singapore'], ['🇭🇰', 'hong kong'],
      ['🇺🇳', 'united nations'], ['🇪🇺', 'european union'],
    ],
  },
]

// Flat lookup for quick keyword search across all categories.
export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap((c) => c.emojis)
